---
- name: update ACLs on nexus kit
  hosts: nexus9k3
  gather_facts: false
  vars:
#    parse_file: cac-nexus-nexus9k2.txt

    save_now: false #reset this here or via extravars if this should be saved

  tasks:
  - name: create the parse file variable manually
    ansible.builtin.set_fact:
#      parse_file: "{{ inventory_hostname }}-acl"
      parse_file: "{{ inventory_hostname }}"
#      just_acls: "{{ lookup('ansible.builtin.file', inventory_hostname) | regex_search('ip access-list +[^\n]+', multiline=True) }}"
#      just_acls: "{{ lookup('ansible.builtin.file', inventory_hostname) | regex_search('ip\\s+access-list\\s+(\\S+)\\s+(.*)', multiline=True) }}"
#      just_acls: "{{ lookup('ansible.builtin.file', inventory_hostname) | regex_search('ip\\s+access-list\\s+(\\S+)\\s+(.*)') }}"
      just_acls: "{{ lookup('ansible.builtin.file', inventory_hostname) | regex_search('ip access-list.*(?:\\n {2}\\d+.*)+') }}"

  ### BLOCK START ###
  - name: block if a parse file is specified
    when: parse_file is defined
    block: 
    - name: Parse given config to structured data
      cisco.nxos.nxos_acls:
#        running_config: "{{ lookup('file', parse_file) }}"
        running_config: "{{ just_acls }}"
  #      running_config: |
  #        ip access-list ACL1v4
  #          50 deny tcp any lt 55 192.0.2.64 0.0.0.255 ack fin
  #        ipv6 access-list ACL1v6
  #          10 permit sctp any any
        state: parsed
      register: parsed

#    - name: debug
#      ansible.builtin.debug:
#        var: parsed

    - name: Replace NTP config with the provided.  Not merge, but replace
      cisco.nxos.nxos_acls:
        config: "{{ parsed.parsed }}"
        state: replaced
      register: result
  ### BLOCK STOP ###

  - name: save when required
    when: save_now == true and result.changed == true
    cisco.nxos.nxos_config:
      save_when: always