---
- name: update passwords on nexus kit
  hosts: nexus9k3
  gather_facts: false
  vars:
    username: admin
    new_password: lab
    user_role: network-admin
    save_now: false
  tasks:
  - name: create a new user
    cisco.nxos.nxos_user:
      name: "{{ username }}"
      configured_password: "{{ new_password }}"
      role: "{{ user_role }}"
      state: present
    register: result

  - name: save when required
    when: save_now == true and result.changed == true
    cisco.nxos.nxos_config:
      save_when: always